version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15-alpine
    container_name: nest_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_template_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis_test:
    image: redis:7-alpine
    container_name: nest_redis_test
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nest_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  rabbitmq_test:
    image: rabbitmq:3-management-alpine
    container_name: nest_rabbitmq_test
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_test_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
  redis_test_data:
  rabbitmq_data:
  rabbitmq_test_data: